import type { Metadata } from "next";
import {Nunito} from "next/font/google";
import "./globals.css";

import { Container } from "./components/Container";
import { Navbar } from "./components/navbar/Navbar";
import { Toast } from "./providers/Toast";
import { ClientOnly } from "./components/ClientOnly";
import { RegisterModal } from "./components/modal/RegisterModal";
import { SignInModal } from "./components/modal/SignInModal";

import prisma from "@/app/libs/prismadb"
import { getCurrentUser } from "./action/getCurrentUser";
import { RentModal } from "./components/modal/RentModal";
import { CategoryList } from "./components/CategoryList";
import { SearchModal } from "./components/modal/SearchModal";
import { Loader } from "./components/Loader";

const font= Nunito({subsets:["latin"]})

export const metadata: Metadata = {
  title: "Create Airbnb Clone",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const users  = await prisma.user.findMany({})
  const emails = users.map((user)=> user.email) as string[]

  const curUser = await getCurrentUser() 
  return (
    <html lang="en">
      <body
        className={font.className}>
          <ClientOnly>
            <Container>
              <Toast />
              <Navbar curUser={curUser}/>
              <CategoryList />
              <RegisterModal emails={emails}/>
              <SignInModal />
              <RentModal />
              {/* <Loader /> */}
              <SearchModal />
              {children}
            </Container>
          </ClientOnly>
      </body>
    </html>
  );
}
